name: Generate dragon
on:
  push: 
    branches:
      - 'main/**'
      - '!feature/**'
  workflow_dispatch:
    inputs:
      env:
        description: Which env should be running
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Staging
          - Prod
      test:
        required: true 
        default: true
        type: boolean
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: Github-context
        if: github.ref == 'refs/heads/main'
        run: echo "Main branch"

      - name: update file
        run: cowsay -f dragon "Run for cover, I am Dragon" >> dragon.txt

      - name: Upload file
        uses: actions/upload-artifact@v7.0.0
        with:
          name: dragon-file
          path: ./dragon.txt

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        uses: actions/download-artifact@v8.0.0
        with:
          name: dragon-file
          
      - name: Grep file
        run: grep -i dragon dragon.txt

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        uses: actions/download-artifact@v8.0.0
        with:
          name: dragon-file
          
      - name: Cat file
        run: cat dragon.txt
