name: Generate dragon
on:
  push: 
  workflow_dispatch:
jobs:
  asc_job:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: list  files
        run: ls -l
        
      - name: Run shell script
        run: |
          chmod 755 ./ascii.sh
          sh ./ascii.sh

